이메일 인증 테스트
Chanqun-Co/carsharing pull request #22
Opened 2023-02-11 17:13 UTC by ksh9241

EmailAuthTest
    - 이메일 인증 코드 생성 테스트
    - 이메일 인증 횟수 체크 테스트

2023-02-11 22:53 UTC, chanqun requested changes

2023-02-11 22:53 UTC, chanqun commented on core/src/test/kotlin/io/sharing/server/core/emailauth/domain/EmailAuthTest.kt
> +        val MAX_RETRY_COUNT = 5
- MAR_RETRY_COUNT, EmailAuth에서 가져와도 될 것 같습니다.
- 이메일 인증 횟수 체크 실패만 있는데, 성공도 있어야할 것 같습니다.
- Assertions. static import 하면 좋겠습니다.
- 지금 테스트 코드는 우리가 원하는 Exception인지 모르므로 상속하는 TooManyAuthCodeRetryException : Exception() 을 만들고 그 에러를 반환하는지 테스트 해보면 좋을 것 같습니다.

- 인증 횟수 체크 기능은, 인증코드 검사라는 기능을 만들어서 안에서 진행해야 하는 것은 아닌가 생각이 듭니다.

2023-02-11 22:53 UTC, chanqun commented on core/src/test/kotlin/io/sharing/server/core/emailauth/domain/EmailAuthTest.kt
> +        emailAuth.generateAuthCode()
데이터 세팅 부분과 생성하는 부분 구분 가능하도록 개행 있었으면 좋겠습니다.

2023-02-11 22:53 UTC, chanqun commented on core/src/main/kotlin/io/sharing/server/core/emailauth/domain/EmailAuth.kt
> +    /** 인증 시도 횟수 - 5회 */
5회 설명은 아래에서 설정해주기 때문에 여기에 없어도 될 것 같습니다.

2023-02-11 22:53 UTC, chanqun commented on core/src/main/kotlin/io/sharing/server/core/emailauth/domain/EmailAuth.kt
> +    /** 인증 만료 시간 - 인증코드 발급 후 5분 */
여기도 인증 시도 횟수 주석과 비슷

2023-02-11 22:53 UTC, chanqun commented on core/src/main/kotlin/io/sharing/server/core/emailauth/domain/EmailAuth.kt
> +        expiredTime = LocalDateTime.now().plusMinutes(5)
5분을 EXPIRED_MINUTES으로 빼는 것이 좋아보입니다.

010712같은 수가 안 나오게 한 것이 의도가 아니라면
authCode 만드는 부분은 String.format("%06d", SecureRandom().nextInt(1_000_000)) 만들어도 충분해보입니다.

2023-02-11 23:11 UTC, woogiekim requested changes

2023-02-11 23:11 UTC, woogiekim commented on core/src/main/kotlin/io/sharing/server/core/emailauth/domain/EmailAuth.kt
> +    fun generateAuthCode() {
authCode 생성할때 authRetry 도 초기화 해주어야 할 듯한데,
그게 아니라면 authRetry 설정은 언제 해주는 것인지 궁금하네요
혹시, 빠진거라면 넣어주는게 좋을거같습니다.

2023-02-11 23:11 UTC, woogiekim commented on core/src/test/kotlin/io/sharing/server/core/emailauth/domain/EmailAuthTest.kt
> +        val createdEmailAuth = EmailAuth.create(email = email)
개행을 해주는 것이 좋을거 같습니다.

2023-02-11 23:11 UTC, woogiekim commented on core/src/test/kotlin/io/sharing/server/core/emailauth/domain/EmailAuthTest.kt
> +    fun `이메일 인증 횟수 체크 - 예외처리`() {
예외에 걸리는 케이스에 대해서만 테스트하네요 안걸리는 케이스도 테스트 해줘야할거같습니다.

1. 성공 케이스
2. 실패 케이스 1
3. 실패 케이스 2
4. ...

위 순서대로 테스트 해주는 것을 지향하고 있습니다.

2023-02-11 23:26 UTC, woogiekim commented on core/src/main/kotlin/io/sharing/server/core/emailauth/domain/EmailAuth.kt
> +            throw Exception("이메일 인증 시도 횟수 초과")
중복되는 리뷰로 Resolve 처리함

2023-02-11 23:26 UTC, woogiekim commented on core/src/test/kotlin/io/sharing/server/core/emailauth/domain/EmailAuthTest.kt
> +        val MAX_RETRY_COUNT = 5
중복되는 리뷰로 Resolve 처리함

2023-02-11 23:27 UTC, woogiekim commented on core/src/test/kotlin/io/sharing/server/core/emailauth/domain/EmailAuthTest.kt
> +        Assertions.assertThatException().isThrownBy {
중복되는 리뷰로 Resolve 처리함

2023-02-11 23:27 UTC, woogiekim commented on core/src/test/kotlin/io/sharing/server/core/emailauth/domain/EmailAuthTest.kt
> +        emailAuth.generateAuthCode()
중복되는 리뷰로 Resolve 처리함

2023-02-11 23:27 UTC, woogiekim commented on core/src/test/kotlin/io/sharing/server/core/emailauth/domain/EmailAuthTest.kt
> +        val createdEmailAuth = EmailAuth.create(email = email)
중복되는 리뷰로 Resolve 처리함

2023-02-12 02:40 UTC, woogiekim commented on core/src/main/kotlin/io/sharing/server/core/emailauth/domain/EmailAuth.kt
> +            throw Exception("이메일 인증 시도 횟수 초과")
- check*: 어떠한 로직 확인 후 boolean 타입으로 리턴.

- validate*: 어떠한 로직이 유효한가 검사한 후 유효하지않으면 예외 발생.

보통의 경우 이런식으로 다룹니다.

2023-02-12 08:35 UTC, kimzerovirus commented on core/src/main/kotlin/io/sharing/server/core/emailauth/domain/EmailAuth.kt
> +        expiredTime = LocalDateTime.now().plusMinutes(5)
어제 작성할 때는 무의식적으로 첫째자리가 1부터 시작한다고 생각했는데 개수와 같은게 아니라 인증코드이니 말씀하신대로 첫째자리가 0부터 시작하는게 맞는것 같습니다.

2023-02-12 08:37 UTC, kimzerovirus commented on core/src/main/kotlin/io/sharing/server/core/emailauth/domain/EmailAuth.kt
> +    fun generateAuthCode() {
넵, 생각하신대로 authCode 가 생성될 때 authRetry 도 초기화 되는게 맞습니다. 
이 부분 주석 추가하도록 하겠습니다.

2023-02-13 06:37 UTC, woogiekim commented on core/src/main/kotlin/io/sharing/server/core/emailauth/domain/EmailAuth.kt
> +        expiredTime = LocalDateTime.now().plusMinutes(5)
SecureRandom 으로 생성하면, 매번 객체 생성이 되는 문제가 있을거같습니다.
정적으로 객체를 만들어놓고 사용하는것이 더 좋을거같습니다.

2023-02-13 06:40 UTC, woogiekim commented on core/src/main/kotlin/io/sharing/server/core/emailauth/domain/EmailAuth.kt
> +        expiredTime = LocalDateTime.now().plusMinutes(5)
테스트

2023-02-13 14:33 UTC, NewEgoDoc approved these changes

2023-02-13 14:41 UTC, kimzerovirus approved these changes

2023-02-14 00:16 UTC, chanqun requested changes

2023-02-14 00:16 UTC, chanqun commented on core/src/test/kotlin/io/sharing/server/core/emailauth/domain/EmailAuthTest.kt
> +    @Test
@ParameterizedTest 있습니다 한 번 찾아봐 주세요

2023-02-14 00:16 UTC, chanqun commented on core/src/test/kotlin/io/sharing/server/core/emailauth/domain/EmailAuthTest.kt
> +        val emailAuthCode = "123456"
val emailAuth = createEmailAuth().apply {
 this.authCode = "123456"
}
처럼 apply 적용 했으면 좋겠다는 리뷰 남긴거 한 번 더 확인해 주시면 좋겠습니다.

2023-02-14 00:16 UTC, chanqun commented on core/src/test/kotlin/io/sharing/server/core/emailauth/domain/EmailAuthTest.kt
> +        assertThat(result).isFalse()
메소드 실행과 체크하는 것은 다른 생각 단위라 개행 필요

2023-02-14 00:16 UTC, chanqun commented on core/src/test/kotlin/io/sharing/server/core/emailauth/domain/EmailAuthTest.kt
> +        assertThat(result).isTrue()
apply 적용, 
생각 단위 다름 개행 필요 밑에 적었습니다.

2023-02-14 00:16 UTC, chanqun commented on core/src/main/kotlin/io/sharing/server/core/emailauth/domain/EmailAuth.kt
> +            increaseAuthRetry()
increaseAuthRetry 메소드 호출 했는데 아무 정보 없이 validateRetryCount까지 호출하는 것은 큰 문제가 될 수 있습니다.

checkEmailAuth 자체가 authRetry 하는 것이므로 따로 메소드 분리 할 필요 없을 것 같습니다.

위에서 시간과 횟수를 확인하고
return authCode == emailAuthCode 반환 하는 것이 좋아 보이네요

2023-02-14 00:16 UTC, chanqun commented on core/src/main/kotlin/io/sharing/server/core/emailauth/domain/EmailAuth.kt
> +        expiredTime = LocalDateTime.now().plusMinutes(5)
5분을 EXPIRED_MINUTES 뺴는 부분 리뷰 반영이 없는 것 같습니다.

2023-02-14 00:16 UTC, chanqun commented on core/src/main/kotlin/io/sharing/server/core/support/exception/TooManyAuthCodeRetryException.kt
> +class TooManyAuthCodeRetryException(val error: TooManyAuthCodeRetryError = TooManyAuthCodeRetryError.UNKNOWN) : Exception(error.messageKey)
TooManyAuthCodeRetryException는 메세지 키가 따로 필요 없이
`class TooManyAuthCodeRetryException : Exception()`
이면 충분할 것 같습니다.

커스텀 익셉션은 비즈니스 로직에 대해 특별히 정의한 익셉션이라 위 경우와 많이 다릅니다.

2023-02-14 00:16 UTC, chanqun commented on core/src/test/kotlin/io/sharing/server/core/emailauth/domain/EmailAuthTest.kt
> +
횟수 증가 자체가 로직이 아니고
체크했더니 횟수가 증가했다가 맞을 것 같네요

2023-02-14 00:16 UTC, chanqun commented on core/src/test/kotlin/io/sharing/server/core/emailauth/domain/EmailAuthTest.kt
> +                .hasMessage(EXCEED_RETRY_COUNT.messageKey)
위에 TooManyAuthCodeRetryException에 설명 보시고
그렇게 변경할 경우 메세지 까지 확인할 필요는 없을 것 같네요

2023-02-14 00:23 UTC, woogiekim commented on core/src/test/kotlin/io/sharing/server/core/emailauth/domain/EmailAuthTest.kt
> +    @Test
아니면, `authRetry` 를 `MAX_RETRY_COUNT`로 적용해놓고 테스트 하는 방법도 좋을거같긴합니다.

2023-02-14 12:50 UTC, NewEgoDoc approved these changes
예제 잘봤습니다

2023-02-14 13:04 UTC, chanqun approved these changes

2023-02-14 13:58 UTC, woogiekim approved these changes
고생하셨습니다 👍

2023-02-15 02:41 UTC, merged