carsharing-24 Product 도메인 초안 작성
Chanqun-Co/carsharing pull request #25
Opened 2023-02-23 15:05 UTC by NewEgoDoc

🛠️ 작업 내용
- Product 도메인 생성 테스트
- Product 도메인 초안 만들기

🗨️ 기타
- 설명부분에 @Lob인지 개인적으로 궁금해서 찾아보고 PR 다시 날릴수도 있습니다 ㅠ

2023-02-23 20:37 UTC, woogiekim requested changes

2023-02-23 20:37 UTC, woogiekim commented on core/src/main/kotlin/io/sharing/server/core/product/domain/Product.kt
> +    var fee: Int,
네이밍 `rentalFee` 는 어떨까요?

그리고 대여료의 화폐기준이 어떻게 되는지 궁금하네요

2023-02-23 20:37 UTC, woogiekim commented on core/src/main/kotlin/io/sharing/server/core/product/domain/Product.kt
> +class Product(
현재 구조에서는
유저 한 명이 같은 번호의 차량을 상품으로 여러번 등록할 수 있는데, 이게 비즈니스 규칙에 맞는가? 생각해 보면 좋겠습니다.

규칙이 아니라면,
유저와 차량번호로 유니크키를 만들어 두는게 좋겠습니다.

2023-02-23 23:59 UTC, chanqun commented on core/src/main/kotlin/io/sharing/server/core/product/domain/Product.kt
> +//    var images: List<Image>
image는 string 키 값만 가지고 등록하는 법을 한 번 생각해봐야할 것 같습니다

2023-02-24 00:03 UTC, chanqun commented on core/src/test/kotlin/io/sharing/server/core/product/domain/ProductTest.kt
> +        assertThat(product.user).isNotNull
jpa entity equality도 알고 있어도 한번 보는게 좋을 것 같네요
https://www.baeldung.com/jpa-entity-equality

2023-02-24 00:04 UTC, chanqun commented on core/src/main/kotlin/io/sharing/server/core/product/domain/Product.kt
> +class Product(
엔티티에 대한 네이밍(필요한 경우에는 설명)도 넣어주세요

2023-02-24 00:06 UTC, chanqun commented on core/src/main/kotlin/io/sharing/server/core/product/domain/Location.kt
> +    Seoul, California, Tokyo
location 기존 유저쪽에 region도 있는 것으로 알고 있는데 다르게 써야할 이유가 있을까요

커밋전에 ktlint를 한번 돌려주세요

2023-02-24 07:23 UTC, kimzerovirus commented on core/src/main/kotlin/io/sharing/server/core/product/domain/Product.kt
> +    @Column(columnDefinition = "TEXT")
@Lob 어노테이션은 large obejct 로 blob, clob 형식 등으로 변환되어 저장되고 TEXT 는 varchar 보다 더 큰 데이터형으로 SQL표준 데이터형이 아닌 MySQL 에서 사용하는 데이터형입니다. varchar 형과 비교하면 다음과 같은 차이가 있다고 합니다.

- text: 최대 크기를 따로 제한 할 수 없고 크기는 무조건 65535
- varchar: 최대 크기를 제한할 수 있으며, 범위는 1 ~ 65535

따라서  어느쪽을 사용해도 상관없을 것 같습니다.

데이터형 참고표를 보면 오라클의 CLOB 이 MySQL의 LONGTEXT로 변환됨을 확인할 수 있습니다.
https://cloud.google.com/solutions/migrating-oracle-users-to-mysql-data-users-tables?hl=ko

2023-02-24 23:42 UTC, chanqun commented on core/src/main/kotlin/io/sharing/server/core/product/domain/Product.kt
> +    @Column(columnDefinition = "TEXT")
상품엔티티 위에 주석만 추가해주세요

2023-02-24 23:43 UTC, chanqun approved these changes
상품 위에 주석 추가해주시고 

/** 상태정보 */
    @Enumerated(EnumType.STRING)
    @Column(length = 20, nullable = false)
    var productStatus: ProductStatus,

-> 상태
productStatus -> status 라고 해도 될 것 같습니다. 상품 내에 있는 상태이기 떄문에 명확합니다

2023-02-25 05:46 UTC, woogiekim approved these changes

2023-02-25 07:40 UTC, merged

2023-02-25 09:12 UTC, kimzerovirus commented on core/src/main/kotlin/io/sharing/server/core/product/domain/Product.kt
> +    var fee: Int,
일단 단위는 원화로만 생각하고 있습니다.