carsharing-30 상품 엔티티에 상품 이미지 추가 및 테스트
Chanqun-Co/carsharing pull request #31
Opened 2023-03-01 13:45 UTC by kimzerovirus

2023-03-01 13:56 UTC, chanqun approved these changes

2023-03-01 13:56 UTC, chanqun commented on core/src/main/kotlin/io/sharing/server/core/carmodel/domain/CarModel.kt
> +) : BaseAggregateRoot<CarModel>()
린트 돌리기 습관 있어야함

2023-03-01 13:56 UTC, chanqun commented on core/src/main/kotlin/io/sharing/server/core/product/domain/Product.kt
> +    val images: MutableList<ProductImage> = mutableListOf(),
따로 ProductImage 안 만들고 String으로 하면 좋을 것 같습니다.

2023-03-01 14:02 UTC, kimzerovirus commented on core/src/main/kotlin/io/sharing/server/core/product/domain/Product.kt
> +    val images: MutableList<ProductImage> = mutableListOf(),
넵, 그냥 String으로 할까 다른 컬럼이 필요할 수도 있지 있으니 객체로 따로 뺄까 고민했는데 필요하게 되면 고치는게 낫겠네요

2023-03-01 14:06 UTC, woogiekim requested changes
늦은시간까지 모여서 개발하시는 열정에 많이 배웁니다.

2023-03-01 14:06 UTC, woogiekim commented on core/src/test/kotlin/io/sharing/server/core/product/domain/ProductTest.kt
> +        assertThat(product.images[0].url).isEqualTo("test-url1")
이미지 하나만 검증하는 것이 과연 맞는것일까 라는 생각이 듭니다.
준비한 데이터에 대한 모든 검증을 해주는것이 좋다는 생각입니다.

2023-03-01 14:06 UTC, woogiekim commented on core/src/test/kotlin/io/sharing/server/core/product/domain/ProductTest.kt
> +        }
```suggestion
        (1..10).forEach {
            product.addImage(createProductImage("test-url$it"))
        }
```

위 코드와 같이 작성하는 편이 더욱 코틀린스러울거같습니다.

2023-03-01 14:09 UTC, chanqun commented on core/src/main/kotlin/io/sharing/server/core/product/domain/Product.kt
> +}
스래드 댓글 남기긴했는데 elementCollection은 값들이 전부 삭제되고 바뀌는 형식이라
메소드를 전체 이미지 관리 해주는 것으로 바꾸면 좋을 것 같아요

2023-03-01 14:11 UTC, chanqun commented on core/src/test/kotlin/io/sharing/server/core/product/domain/ProductTest.kt
> +        assertThat(product.images[0].url).isEqualTo("test-url1")
assertj - containsExactlyInAnyOrder() 함 확인해보세여

2023-03-02 01:14 UTC, woogiekim approved these changes
고생하셨습니다. 👍 

추가 리뷰는 슬랙채널 스레드로 남겼으니
반영하고 머지 해주시면 됩니다.

2023-03-02 05:46 UTC, merged