carsharing-33 Reservation 테스트 및 엔티티 작성
Chanqun-Co/carsharing pull request #34
Opened 2023-03-03 11:28 UTC by NewEgoDoc

- 생성 테스트 및 생성 실패 케이스(checkin-checkout 시간 제약) 생성
- Reservation 엔티티 생성

2023-03-03 13:05 UTC, woogiekim requested changes
PR명을 명학하게 할 필요성이 있어보입니다.
테스트 코드는 당연한것이라는 생각이라 별도로 테스트 코그만 작성해 PR하는 것 아니면 언급할 필요는 없어보입니다.

리뷰내용 확인보시고 수정해주시면 될거같습니다.

그리고 given when then 주석은 합의가 필요해 보이니 논의를 주도해보심은 어떨까 싶습니다.

2023-03-03 13:05 UTC, woogiekim commented on core/src/test/kotlin/io/sharing/server/core/reservation/domain/ReservationTest.kt
> +    }
경계값에 대한 테스트만 하면 되지 않을까 싶습니다.

2023-03-03 14:39 UTC, chanqun commented on core/src/main/kotlin/io/sharing/server/core/reservation/domain/Reservation.kt
> +    /** 등록차량 정보 */
등록차량 정보가 아니고 우리는 상품이라고 약속했으니 유비쿼터스 랭귀지 지켜주세요

2023-03-03 14:40 UTC, chanqun commented on core/src/main/kotlin/io/sharing/server/core/reservation/domain/Reservation.kt
> +    /** 예약상태 */
예약상태도 명확하긴하지만 예약 내에 있는 상태로 명확하니 그냥 상태라고 남겨도 괜찮을 것 같습니다.
다른 곳에 남겼던 리뷰와 비슷합니다.

2023-03-04 03:39 UTC, woogiekim commented on core/src/main/kotlin/io/sharing/server/core/reservation/domain/Reservation.kt
> +        fun create(product: Product, checkIn: LocalDateTime, checkOut: LocalDateTime): Reservation {
유효성검사 하는 부분을 놓치고 리뷰한것같습니다.

컴패니언 오브젝트를 써야할 이유가 있네요.

추가로 이벤트도 터트려주면 좋을거같습니다.

2023-03-04 07:45 UTC, woogiekim approved these changes
1. 상수로 바꾼부분 const 유지하는게 좋겠다.
2. 만든 상수를 적절히 사용했으면 좋겠다. (예약 생성 테스트 부분)
3. 테스트 데이터준비할때에 테스트 해야 할 부분에 대해서 명시적으로 보여주면 더 좋겠다.
4. 사용하지 않을 부분을 미리 만들지 않는것이 좋겠다. (xxView.kt 만들어 놓은 부분)
5. 테스트 데이터 세팅시 유기적으로 관계가 있고 복잡해서 까다로운 경우가 아니면 repository 이용해서 세팅하는 편이 더 좋겠다.

추가적인 리뷰내용입니다.
반영해주시고 머지해주시면되겠습니다. :)

2023-03-05 08:23 UTC, merged