carsharing-29 유저 상태변경 테스트
Chanqun-Co/carsharing pull request #35
Opened 2023-03-03 12:01 UTC by ksh9241

2023-03-03 13:26 UTC, woogiekim requested changes
첫 유스케이스 작성이네요.
처음 운을 떼어보는게 쉽지만은 않을거라 생각합니다.
코멘트 확인해주시고 수정해주시면 좋겠습니다. :)

2023-03-03 13:26 UTC, woogiekim commented on api/src/main/kotlin/io/sharing/server/api/user/adapter/inp/web/UserInactiveView.kt
> +class UserInactiveView(
유스케이스와 같은 조합형식을 따라주는게 더 일관성있을거같습니다

```suggestion
class InactivateUserView(
```

2023-03-03 13:26 UTC, woogiekim commented on core/src/main/kotlin/io/sharing/server/core/user/application/port/inp/InactiveUser.kt
> +interface InactiveUser {
inactive는 동사가 아닙니다.

inactivate이 더 좋을거같습니다.

2023-03-03 13:26 UTC, woogiekim commented on core/src/main/kotlin/io/sharing/server/core/user/application/port/inp/InactiveUser.kt
> +     * @throws TisException()
에러코드 명시가 더 좋을거같습니다.

2023-03-03 13:26 UTC, woogiekim commented on core/src/main/kotlin/io/sharing/server/core/user/application/port/inp/InactiveUser.kt
> +// )
일관성과 오버로딩 문제때문에 써야합니다.

2023-03-03 13:26 UTC, woogiekim commented on core/src/main/kotlin/io/sharing/server/core/user/application/service/UserService.kt
> +        userRepository.save(user)
더티체킹이 됩니다 명시적으로 save 할 필요없습니다.

2023-03-03 13:26 UTC, woogiekim commented on core/src/main/kotlin/io/sharing/server/core/user/domain/User.kt
> +    fun changeToInactive() {
```suggestion
    fun inactivate() {
```

이런 함수명은 어떨까요?

2023-03-03 13:26 UTC, woogiekim commented on core/src/test/kotlin/io/sharing/server/core/user/application/port/inp/InactiveUserTest.kt
> +@RecordApplicationEvents
이벤트 터트리는게 없다면 필요없는 부분입니다.

2023-03-03 13:26 UTC, woogiekim commented on core/src/test/kotlin/io/sharing/server/core/user/application/port/inp/InactiveUserTest.kt
> +    }
테스트는 단 하나인데, 유저 세팅을 이런식으로 할 필요는 없다는 생각입니다

2023-03-03 13:26 UTC, woogiekim commented on core/src/test/kotlin/io/sharing/server/core/user/application/port/inp/InactiveUserTest.kt
> +    fun `유저 삭제`() {
비활성화와 삭제 무엇이 맞나요?
유비쿼터스 랭귀지를 지켜주세요.

2023-03-03 14:33 UTC, chanqun commented on core/src/main/kotlin/io/sharing/server/core/user/application/service/UserService.kt
> +        val user = userRepository.findByIdOrNull(id) ?: throw EntityNotFoundException()
jpa를 사용하고 있긴하지만 EntityNotFoundException는 너무 종속적인 것 같습니다.
화면에서 잘못된 요청을 하고 있는 것이니 IllegalArgument 도 좋아보입니다.

2023-03-03 14:33 UTC, chanqun commented on core/src/main/kotlin/io/sharing/server/core/user/domain/User.kt
> +        this.status = UserStatus.INACTIVE
inactive 하기전에 유저의 상태를 확인할 필요는 없는지도 한번 생각해보면 좋겠네요

2023-03-03 15:38 UTC, ksh9241 commented on api/src/main/kotlin/io/sharing/server/api/user/adapter/inp/web/UserInactiveView.kt
> +class UserInactiveView(
넵 피드백 주신내용 토대로 다시 수정하겠습니다. 감사합니다.

2023-03-03 15:39 UTC, ksh9241 commented on core/src/main/kotlin/io/sharing/server/core/user/application/service/UserService.kt
> +        val user = userRepository.findByIdOrNull(id) ?: throw EntityNotFoundException()
넵 말씀해주신 내용 토대로 다시 수정하겠습니다. 감사합니다

2023-03-04 07:43 UTC, woogiekim approved these changes
1. 상수로 바꾼부분 const 유지하는게 좋겠다.
2. 만든 상수를 적절히 사용했으면 좋겠다. (예약 생성 테스트 부분)
3. 테스트 데이터준비할때에 테스트 해야 할 부분에 대해서 명시적으로 보여주면 더 좋겠다.
4. 사용하지 않을 부분을 미리 만들지 않는것이 좋겠다. (xxView.kt 만들어 놓은 부분)
5. 테스트 데이터 세팅시 유기적으로 관계가 있고 복잡해서 까다로운 경우가 아니면 repository 이용해서 세팅하는 편이 더 좋겠다.

추가적인 리뷰내용입니다.
반영해주시고 머지해주시면되겠습니다. :)

2023-03-04 07:48 UTC, woogiekim commented on core/src/main/kotlin/io/sharing/server/core/user/application/port/inp/InactivateUser.kt
> +     * @throws IllegalArgumentException() 예외처리한다.
예외에 대한 로직 바뀌어서 주석도 변경해줘야겠네요.

2023-03-05 07:55 UTC, NewEgoDoc approved these changes

2023-03-05 10:55 UTC, merged