carsharing-37 상품 상태 변경 기능 추가
Chanqun-Co/carsharing pull request #38
Opened 2023-03-08 05:25 UTC by kimzerovirus

ProductStatus의 REGISTERED를 좀 더 판매 중이라는 의미가 확실히 나타나도록 SELLING 으로 변경하였습니다.

2023-03-09 08:18 UTC, chanqun commented on core/src/main/kotlin/io/sharing/server/core/product/domain/Product.kt
> +    fun onAvailable() {
https://www.wordreference.com/enko/make%20available

makeAvailable 같은 네이밍이 좋을 것 같습니다.
onAvaiable은 available 이벤트 발생시 어떤 일을 한다는 느낌이 드네요

2023-03-09 08:18 UTC, chanqun commented on core/src/main/kotlin/io/sharing/server/core/product/domain/Product.kt
> +    var status: ProductStatus = ProductStatus.AVAILABLE,
등록되었을때 바로 예약이 가능한 것일까요?
기존 REGISTERED는 등록되어서 available하기 전 단계를 보여주는 것이었습니다.

2023-03-09 08:19 UTC, chanqun commented on core/src/main/kotlin/io/sharing/server/core/product/application/service/ProductService.kt
> +package io.sharing.server.core.product.application.service
구현되지 않은 클래스는 따로 이슈를 만들어서 작업하면 좋을 것 같습니다.

2023-03-09 09:52 UTC, woogiekim requested changes

2023-03-09 09:52 UTC, woogiekim commented on core/src/main/kotlin/io/sharing/server/core/product/application/port/inp/CreateProduct.kt
> +class CreateProductCommand()
상품상태변경 이슈와 관련없는 내용이고
구현하지 않는 내용이라면 삭제하는게 좋겠습니다.

상품상태변경 로직과 밀접한 연관이 있지만
구현은 나중에 미루고싶다 이런 경우에는 이해되지만 필요없다고 생각합니다.

---

밀접한 연관 케이스
- 상품상태변경 하고는 외부서비스와 연동

이런 경우 외부서비스 연동 인터페이스를 미리 만들어 둘수는 있다고 생각합니다.

2023-03-09 09:52 UTC, woogiekim commented on core/src/main/kotlin/io/sharing/server/core/product/domain/Product.kt
> +    fun onAvailable() {
onXxx 네이밍은 보통 어떤 메시지를 리슨하고 있는 경우 사용하는 관습이 있습니다.
그런 이유로 헷갈리게 합니다.

다른 이름으로 변경하는게 좋겠습니다.

2023-03-09 09:52 UTC, woogiekim commented on core/src/test/kotlin/io/sharing/server/core/product/domain/ProductTest.kt
> +        val product = createProduct()
UNAVAILABLE 상태가 아니었다는것을 명시해두는 세팅을 해주는편이 더 좋을거같습니다
```suggestion
        val product = createProduct().apply { status = AVAILABLE }
```

2023-03-09 13:20 UTC, kimzerovirus commented on core/src/main/kotlin/io/sharing/server/core/product/application/service/ProductService.kt
> +package io.sharing.server.core.product.application.service
넵 지운다는게 자꾸 까먹네요... 다음 커밋 반영할 때 삭제하겠습니다

2023-03-09 13:26 UTC, kimzerovirus commented on core/src/main/kotlin/io/sharing/server/core/product/domain/Product.kt
> +    var status: ProductStatus = ProductStatus.AVAILABLE,
네 저는 바로 예약 가능하다고 생각했었는데 토의 결과 
처음 등록하고 심사를 거쳐 available 하게 바꾸는 걸로 하기로 했습니다.
따라서 상태를 좀더 세분화해야 할 것 같습니다. 
- 등록
- 심사
- 승인
- 예약 가능한 상태
- 예약 불가능한 상태

2023-03-09 13:28 UTC, kimzerovirus commented on core/src/main/kotlin/io/sharing/server/core/product/application/port/inp/CreateProduct.kt
> +class CreateProductCommand()
넵 다음 커밋에 지우도록 하겠습니다

2023-03-12 03:57 UTC, chanqun commented on core/src/test/kotlin/io/sharing/server/core/product/domain/ProductTest.kt
> +    fun `상품 상태 심사로 변경`() {
테스트 명들이
객체에게 요청하는 커맨드 같은 이름으로 되었으면 좋겠습니다.
상품 상태 심사로 변경은 데이터 중심적입니다. -> 상품 최초 등록 하면 심사 대기 중이다.

2023-03-12 03:57 UTC, chanqun commented on core/src/test/kotlin/io/sharing/server/core/product/domain/ProductTest.kt
> +    @Test
@Parameterizedtest 하고 @EnumSource 있으니 참고해보세요

2023-03-12 03:57 UTC, chanqun commented on core/src/main/kotlin/io/sharing/server/core/product/domain/ProductStatus.kt
> +    SCREENING,
enum 좀 더 고쳐주시고 설명을 추가해야 될 것 같습니다.

2023-03-12 03:57 UTC, chanqun commented on core/src/main/kotlin/io/sharing/server/core/product/domain/Product.kt
> +        require(this.status == ProductStatus.SCREENING || this.status == ProductStatus.UNAVAILABLE)
더 많아지면 enum 한테 요청해도 될 것 같긴하고
|| 보다는 listof 해서 in으로 보면 좀 더 가독성이 올라갈 것 같습니다.

2023-03-12 14:34 UTC, kimzerovirus commented
아래와 같이 상품 상태를 재정의 했습니다.
 - REGISTERED 등록
 - REJECTED 거절
 - AVAILABLE 예약 가능
 - UNAVAILABLE 예약 불가능

2023-03-13 00:53 UTC, woogiekim requested changes

2023-03-13 00:53 UTC, woogiekim commented on core/src/main/kotlin/io/sharing/server/core/product/domain/ProductStatus.kt
> +    UNAVAILABLE
각 상태로 갈 수 있는 상황에 대한 설명이 필요합니다.

관리자인 경우
REGISTERED -> AVAILABLE
REGISTERED -> REJECTED

xxx인 경우
REGISTERED -> AVAILABLE
AVAILABLE -> UNAVAILABLE

위는 예시입니다.

예시로 나열해봤더니
UNAVAILABLE 상태에서 AVAILABLE 로 가려면 어떤 과정이 필요한가?
관리자를 통해 바꿀 수 있는 것인가?
이런 의문도 생기네요

2023-03-13 00:53 UTC, woogiekim commented on core/src/test/kotlin/io/sharing/server/core/product/domain/ProductTest.kt
> +        }
```suggestion
        val product = createProduct(status = REGISTERED)
```

픽스처에 상태도 파라미터로 추가하셨다면, 이용하시는게 더 좋을거같습니다.

2023-03-13 00:53 UTC, woogiekim commented on core/src/main/kotlin/io/sharing/server/core/product/domain/Product.kt
> + * - 관리자는 등록된 상품을 승인 또는 거절을 할 수 있다.
관리자는 어드민일거라는 생각이 들기는 하지만 관리자에 대한 정의가 필요해보입니다.

2023-03-13 00:53 UTC, woogiekim commented on core/src/test/kotlin/io/sharing/server/core/product/domain/ProductTest.kt
> +    fun `등록된 상품을 승인을 할 수 있다`() {
실패케이스 조건 혹은 특이 케이스 (상품 등록할 수 있는 방법이 여러개 존재) 가 아니라면 구체적인 조건이 테스트명에 드러날 필요는 없어보입니다.

```suggestion
    fun `상품 승인 성공`() {
```

2023-03-13 00:53 UTC, woogiekim commented on core/src/test/kotlin/io/sharing/server/core/product/domain/ProductTest.kt
> +    fun `등록 상태가 아니면 상품 승인 할 수 없다`(status: ProductStatus) {
저런 형태 포맷으로 작성해주면 일관성있는 이름으로 작성할 수 있게 되어 가독성으 높일 수 있습니다.

```suggestion
    fun `상품 승인 실패 - 등록 상태가 아닌 경우`(status: ProductStatus) {
```

2023-03-13 18:38 UTC, kimzerovirus commented on core/src/main/kotlin/io/sharing/server/core/product/domain/ProductStatus.kt
> +    UNAVAILABLE
말씀하신 2개의 상태는 호스트가 예약을 받을 때와 안 받을 때를 구분하는 상태로 생각하고 있습니다. 
따라서 호스트에 의해서 양방향으로 바꿀 수 있는 상태입니다. (AVAILABLE -> UNAVAILABLE, UNAVAILABLE -> AVAILABLE)

관리자를 통해 예약 불가능하게 되거나 호스트가 영구적으로 예약을 받을 수 없게 한 상태는 CANCELED라는 상태를 따로 넣는것을 생각했는데 해당 경우는 DB에서 바로 상품을 삭제하는 것이 어떻냐는 의견이 있어 따로 상태로 다루지 않았습니다.

이번 이슈가 너무 길어져서 우선은 승인과 거절까지만 다루고 말씀하신 부분은 다음 이슈에서 다루는건 어떨까요?

2023-03-13 18:41 UTC, kimzerovirus commented on core/src/main/kotlin/io/sharing/server/core/product/domain/Product.kt
> + * - 관리자는 등록된 상품을 승인 또는 거절을 할 수 있다.
넵 말씀하신대로 관리자는 어드민입니다. 관리자에 대한 정의는 팀원들과 논의하고 관리자 이외의 용어들도 위키에 차근차근 정리해두겠습니다.

2023-03-14 00:02 UTC, woogiekim commented on core/src/main/kotlin/io/sharing/server/core/product/domain/ProductStatus.kt
> +    UNAVAILABLE
로직을 넣었으면 하는 의도는 아니었고,  시나리오에 대한 주석이 필요하다고 생각이 들었습니다.
위키에 정리하는것도 좋겠네요

2023-03-14 00:05 UTC, woogiekim approved these changes

2023-03-14 04:12 UTC, merged