carsharing-40 캘린더 엔티티 설계
Chanqun-Co/carsharing pull request #44
Opened 2023-03-11 08:57 UTC by NewEgoDoc

캘린터 엔티티 상태를 설정하고 캘린더 엔티티 생성을 하였습니다

2023-03-11 09:31 UTC, chanqun requested changes

2023-03-11 09:31 UTC, chanqun commented on core/src/main/kotlin/io/sharing/server/core/calendar/domain/Calendar.kt
> +class Calendar(
상품에 대한 예약 불가능한 기간 집합이면
Calendar라는 이름이랑 안 어울리는 것 같은데 Schedule이나 Plan으로 예약이나 예약 불가능한 일정이라고 하면 어땠을까요

2023-03-11 09:31 UTC, chanqun commented on core/src/main/kotlin/io/sharing/server/core/calendar/domain/Calendar.kt
> +        fun create(product: Product, reservation: Reservation? = null, startTime: OffsetDateTime, endTime: OffsetDateTime, calendarType: CalendarType): Calendar {
startTime, endTime이 시간단위라면 검증이 필요할 것 같네요
시간 단위로 할지 10분 단위로 할지 약속이 필요할 것 같습니다.

2023-03-11 09:31 UTC, chanqun commented on core/src/main/kotlin/io/sharing/server/core/calendar/domain/Calendar.kt
> +            // TODO: 해당 상품의 예약리스트를 확인해서 중복되는 시간이 있는 경우 확인
예약리스트가 있는지 확인하는 것은 서비스에서 검증하고 들어왔어야 할 것 같은데요

2023-03-11 09:31 UTC, chanqun commented on core/src/main/kotlin/io/sharing/server/core/calendar/domain/CalendarType.kt
> +    RESERVE, IMPOSSIBLE
RESERVE는 동사입니다. RESERVED 예약된이란 enum이 더 적절해보입니다.
UNAVAILABLE과 IMPOSSIBLE 차이는 무엇인가요?

2023-03-11 09:31 UTC, chanqun commented on core/src/main/kotlin/io/sharing/server/core/calendar/domain/Calendar.kt
> +        fun create(product: Product, reservation: Reservation? = null, startTime: OffsetDateTime, endTime: OffsetDateTime, calendarType: CalendarType): Calendar {
예약과 불가능한 것에 대한 엔티티 생성이 완전히 다른 값을 필요로 하는 것으로 보아
생성함수를 따로 두는 것이 좋아보이네요.

2023-03-11 09:31 UTC, chanqun commented on core/src/test/kotlin/io/sharing/server/core/calendar/domain/CalendarTest.kt
> +    fun `캘린더 생성 - 예약 생성시`() {
예약 생성시, 불가능한 날짜라고 하셨는데

calendar type enum을 쓰고 싶었던 것 같은데 예약 생성시라고 하는 것보다 enum을 넣어주는게 더 이해하기 쉬울 것 같습니다.

2023-03-11 09:33 UTC, chanqun commented on core/src/test/kotlin/io/sharing/server/core/calendar/domain/CalendarTest.kt
> +        val endTime = OffsetDateTime.now()
startTime과 endTime은 같아도 상관 없나보군요?

2023-03-11 09:36 UTC, chanqun commented on core/src/main/kotlin/io/sharing/server/core/calendar/domain/Calendar.kt
> +    @OneToOne(fetch = FetchType.LAZY, optional = true)
optional default true인데 필요 없어 보입니다.

2023-03-11 10:24 UTC, NewEgoDoc commented on core/src/main/kotlin/io/sharing/server/core/calendar/domain/Calendar.kt
> +class Calendar(
Schedule 이라는 이름이 좋을것 같습니다

2023-03-11 10:31 UTC, NewEgoDoc commented on core/src/main/kotlin/io/sharing/server/core/calendar/domain/CalendarType.kt
> +    RESERVE, IMPOSSIBLE
같은 말인것 같습니다. UNAVAILABLE이 더 적절해보입니다 수정하겠습니다

2023-03-12 03:11 UTC, woogiekim reviewed
궁금한 부분 남겼습니다.
확인부탁드립니다. :)

2023-03-12 03:11 UTC, woogiekim commented on core/src/main/kotlin/io/sharing/server/core/calendar/domain/Calendar.kt
> + * 상품에 대한 예약 불가능한 기간 집합
예약불가 기간 집합인데

타입은 예약된것 불가능한것

이런게 있으니, 예약관련 기간 집합인건가 싶은 생각이 드네요

2023-03-12 03:11 UTC, woogiekim commented on core/src/main/kotlin/io/sharing/server/core/calendar/domain/Calendar.kt
> +    val reservation: Reservation? = null,
변경 가능해야할거같네요

2023-03-14 16:53 UTC, NewEgoDoc commented on core/src/main/kotlin/io/sharing/server/core/calendar/domain/Calendar.kt
> +        fun create(product: Product, reservation: Reservation? = null, startTime: OffsetDateTime, endTime: OffsetDateTime, calendarType: CalendarType): Calendar {
startTime과 endTime은 '시간'단위(ex: 2023-01-08 13:00:00Z(Z는 nano의 000을 의미 합니다))로만 입력을 받고
최소 1시간 이후의 시간차를 가져야한다는 정책을 가지고 적용해보려고 합니다

2023-03-15 12:25 UTC, ksh9241 commented on core/src/test/kotlin/io/sharing/server/core/schedule/domain/ScheduleTest.kt
> +class ScheduleTest {
createUnavailableSchedule() 의
예외 케이스도 추가되면 좋을 것 같습니다.

2023-03-15 12:30 UTC, chanqun commented on core/src/main/kotlin/io/sharing/server/core/schedule/domain/Schedule.kt
> +            require(startTime.minute == 0 && startTime.second == 0 && startTime.nano == 0)
시간 확인 하는 것들이 중복이므로 의미 있는 extension을 만드는 것도 좋아보입니다.

2023-03-15 12:30 UTC, chanqun commented on core/src/main/kotlin/io/sharing/server/core/schedule/domain/Schedule.kt
> +
불필요한 개행입니다.

2023-03-15 12:30 UTC, chanqun commented on core/src/main/kotlin/io/sharing/server/core/schedule/domain/Schedule.kt
> +        const val MINIMUM_ARRANGED_TIME = 1L
시간인지 분인지 잘 모르겠네요 시간이면 정확하게 HOUR이라고 명시해주면 좋을 것 같습니다.

2023-03-15 12:30 UTC, chanqun commented on core/src/test/kotlin/io/sharing/server/core/schedule/domain/ScheduleTest.kt
> +    fun `스케줄 생성 - UNAVAILABLE`() {
예외 케이스에 대한 테스트도 필요할 것 같습니다.

2023-03-15 12:34 UTC, chanqun commented on core/src/main/kotlin/io/sharing/server/core/schedule/domain/Schedule.kt
> + * 상품에 대한 예약 불가능한 기간 집합
스케줄에 대한 설명이 상품에 대한 예약 불가능한 기간 집합
예약 불가능한 기간 보다 일정이라고 하는게 좋을지도.. 좀 고민 되네요

2023-03-15 12:34 UTC, chanqun commented on core/src/main/kotlin/io/sharing/server/core/schedule/domain/Schedule.kt
> +    /** 체크타입 */
체크타입은 무엇인가요?

2023-03-15 12:36 UTC, chanqun commented on core/src/main/kotlin/io/sharing/server/core/schedule/domain/Schedule.kt
> +            return Schedule(product = product, reservation = reservation, startTime = reservation.checkIn, endTime = reservation.checkOut, type = ScheduleType.RESERVED).apply {
Reservation에서 checkIn, checkOut 시간도 제약조건 같이 추가해주면 좋을 것 같습니닷

2023-03-15 12:36 UTC, NewEgoDoc reviewed
캘린터 엔티티명 변경 : Calendar -> Schedule
Schedule companion object 의 create 메서드 분리: createReserved, createUnavailable
createUnavailable 생성 테스트: startTime과 endTime 분,초,ms은 '0'이여야 하며, startTime과 endTime의 1시간이상차 가 나야합니다

2023-03-15 15:05 UTC, NewEgoDoc commented on core/src/main/kotlin/io/sharing/server/core/schedule/domain/Schedule.kt
> +            return Schedule(product = product, reservation = reservation, startTime = reservation.checkIn, endTime = reservation.checkOut, type = ScheduleType.RESERVED).apply {
Reservation에서 엔티티가 생성되는 시점에 checkIn, checkOut 시간 제약 유효성 검사가 되는데  Schedule 생성시에도 제약조건을 체크해봐야 할까요?

2023-03-15 15:07 UTC, NewEgoDoc commented on core/src/main/kotlin/io/sharing/server/core/schedule/domain/Schedule.kt
> +    /** 체크타입 */
체크타입은 해당 주체에 관해서 조금더 논의가 필요해 보입니다. (해당 enum의 이름과 각 값의 이름)논의 후에 수정하겠습니다. 감사합니다

2023-03-16 00:06 UTC, chanqun commented on core/src/main/kotlin/io/sharing/server/core/schedule/domain/Schedule.kt
> +            return Schedule(product = product, reservation = reservation, startTime = reservation.checkIn, endTime = reservation.checkOut, type = ScheduleType.RESERVED).apply {
reservation에서 체크인 체크아웃 유효성 검사 없어서 한번 해야할 것 같다는 것입니다.
reservation에 Schedule에 checkIn, checkOut에 대한 시간 단위 확인한 것처럼 추가하면 좋을 것 같습니다.

2023-03-20 15:28 UTC, NewEgoDoc reviewed
1. Reservation 의 10분단위 조건을 추가하였습니다.
2. SchedultType을 Reservation과 Host로 하여 Schedule이 생성되었을 때 해당 주체를 명시하였습니다. Enum 클래스의 설명 참고 부탁드립니다.

2023-03-21 08:02 UTC, chanqun commented on core/src/main/kotlin/io/sharing/server/core/schedule/domain/ScheduleType.kt
> + * RESERVATION: 예약에 의해서 스케줄이 생성
스케줄을 생성한 주체가 RESERVEATION인가요? 차라리 GUEST가 더 맞을 것 같습니다.
스케줄 타입
그냥 RESERVED, BLOCKED 도 괜찮을 것 같습니다.

2023-03-21 08:03 UTC, chanqun commented on core/src/test/kotlin/io/sharing/server/core/reservation/domain/ReservationTest.kt
> +    @CsvSource("2023-03-15T12:11:00.001Z", "2023-03-15T12:10:01.000Z", "2023-03-15T12:10:00.001Z")
이것 또한 익스텐션으로 분리할경우 로직이 응집될 것 같고 같이 테스트하면 좋을 것 같아요

코틀린 익스텐션 공부해주세욥

2023-03-21 08:49 UTC, woogiekim requested changes
ScheduleTest 는 다시 시나리오와 불변식을 생각해보고 짜보셔야할거같습니다.

2023-03-21 08:49 UTC, woogiekim commented on core/src/main/kotlin/io/sharing/server/core/schedule/domain/Schedule.kt
> +        }
예약할 수 있는 기간에 대한 플랜에 대한 책임을 Schedule 객체에게 준것인데 예약에서 시간체크를 또해버리면 응집도가 떨어지는 상황이 되어버리는거 같다는 생각이 듭니다.

Schedule에게 예약 가능한 플랜인지 판단하게 일임한다는 내용을 도메인 모델링에 남겨놓는 것이 좋겠습니다.

2023-03-21 08:49 UTC, woogiekim commented on core/src/main/kotlin/io/sharing/server/core/reservation/domain/Reservation.kt
> +        private fun checkTimeOnTheMinute(time: OffsetDateTime): Boolean {
1. check 로 시작하는 함수가 boolean 리턴하는 것이 이상합니다.
2. checkTimeOnTheMinute 은 의도를 드러내는 이름이 아닌거같습니다. 뭘 하고싶은것인지 생각해볼 필요가 있어보이네요

2023-03-21 08:49 UTC, woogiekim commented on core/src/main/kotlin/io/sharing/server/core/reservation/domain/Reservation.kt
> +            return time.second == 0 && time.nano == 0 && time.minute % 10 == 0
10 을 상수로 빼는게 더 좋지 않을까 싶긴합니다.

2023-03-21 08:49 UTC, woogiekim commented on core/src/test/kotlin/io/sharing/server/core/schedule/domain/ScheduleTest.kt
> +    fun `스케줄 생성 - UNAVAILABLE`() {
스케줄 생성 - RESERVED
스케줄 생성 - UNAVAILABLE

타입을 기준으로 생각한거라면 테스트명이 이상합니다.
여러가지 용어를 사용하기 시작하면, 혼란이 옵니다.
유비쿼터스랭귀지를 지켜주는 것이 좋겠습니다.

2023-03-21 12:03 UTC, NewEgoDoc commented on core/src/main/kotlin/io/sharing/server/core/schedule/domain/Schedule.kt
> +        private fun checkTimeOnTheHour(time: OffsetDateTime): Boolean {
네 공부후에 extension 적용하겠습니다

2023-03-21 12:04 UTC, NewEgoDoc commented on core/src/main/kotlin/io/sharing/server/core/schedule/domain/Schedule.kt
> + * 스케줄에 없는 시간은 예약 가능한 시간
해당 내용은 말씀해주신데로 적용하겠습니다 감사합니다

2023-03-21 12:07 UTC, NewEgoDoc commented on core/src/main/kotlin/io/sharing/server/core/schedule/domain/Schedule.kt
> +        }
Schedule이 시간체크라는 책임을 일임하게 되면 응집도가 올라간다는 말씀이시네요. 감사합니다 적용하겠습니다

2023-03-21 12:11 UTC, NewEgoDoc commented on core/src/main/kotlin/io/sharing/server/core/reservation/domain/Reservation.kt
> +        private fun checkTimeOnTheMinute(time: OffsetDateTime): Boolean {
check으로 시작하는 이름은 보통 boolean을 리턴하는 메소드 명인지 알았습니다. 2번과 마찬가지로 좀더 생각해봐야겠습니다

2023-03-21 16:25 UTC, NewEgoDoc reviewed
- Reservation의 생성 후 Schedule에 checkin과 checkout의 시간 범위에 대한 체크를 위임했습니다.
- ScheduleType을 RESERVED,BLOCKED 로 수정하였습니다
- extension 함수 'isOnTheHour()'를 추가하였습니다.

2023-03-28 05:53 UTC, chanqun approved these changes

2023-03-28 05:53 UTC, chanqun commented on core/src/main/kotlin/io/sharing/server/core/schedule/domain/Schedule.kt
> +        const val MINIMUM_RESERVABLE_HOUR = 2L
MINIMUM_RESERVABLE_HOUR, MINIMUM_ARRANGED_HOUR 차이는 무엇인가요?

2023-03-28 05:53 UTC, chanqun commented on core/src/main/kotlin/io/sharing/server/core/schedule/domain/Schedule.kt
> +        private fun isValidTime(time: OffsetDateTime): Boolean {
isSharp, 정도가 적당할 것 같습니다.
예전에 onTime 쓰셨는데 의도하신 바랑 다른 의미라서 거부감이 있었네요
https://confusingtimes.tistory.com/1430

2023-03-28 05:55 UTC, woogiekim approved these changes

2023-03-28 07:05 UTC, NewEgoDoc commented on core/src/main/kotlin/io/sharing/server/core/schedule/domain/Schedule.kt
> +        const val MINIMUM_RESERVABLE_HOUR = 2L
wiki에 requirement에 기술되어 있는
- 예약 대여시간은 최소 2시간이여야 한다.
- Host가 불가능한 시간대를 설정할 때는 1시간 이상 으로 정의한다.
내용을 상수로 표현했습니다. 최대한 의미가 드러나게 기술 한것 같은데 그렇지 못한것 같습니다. wiki 모델링 섹션에도 기술 해놓겠습니다.

2023-03-28 08:20 UTC, merged