carsharing-52 예약 상태 변경 기능 개발
Chanqun-Co/carsharing pull request #56
Opened 2023-04-02 08:52 UTC by NewEgoDoc

ReservationStatus의 **isAbleToChangeTo()** 메소드를 통해 다음으로 넘어갈수 있는 status를 체크할 수 있게 만들었습니다.
Reservation에서 **changeStatus()** 추가 하여 isAbleToChangeTo()통해 상태체크와 상태 변경를 할 수 있게 하였습니다.

2023-04-02 14:21 UTC, chanqun requested changes

2023-04-02 14:21 UTC, chanqun commented on core/src/main/kotlin/io/sharing/server/core/reservation/domain/Reservation.kt
> +        check(this.status.isAbleToChangeTo(status))
개행이 필요합니다

2023-04-02 14:21 UTC, chanqun commented on core/src/main/kotlin/io/sharing/server/core/reservation/domain/Reservation.kt
> +    fun changeStatus(status: ReservationStatus) {
상품 승인이나 거절을 통한 상태변경이 필요하지 않을까요
changeStatus는 언제 사용하는지 모르겠습니다.

2023-04-02 14:21 UTC, chanqun commented on core/src/main/kotlin/io/sharing/server/core/reservation/domain/ReservationStatus.kt
> +        return false
개행이 필요합니다

2023-04-02 14:21 UTC, chanqun commented on core/src/main/kotlin/io/sharing/server/core/reservation/domain/ReservationStatus.kt
> +        for (next in nextStatuses) {
return status in nextStatuses 이면 충분할 것 같습니다.

2023-04-02 14:21 UTC, chanqun commented on core/src/test/kotlin/io/sharing/server/core/reservation/domain/ReservationStatusTest.kt
> +    fun `예약 상태 변경 TURE - PENDING to APPROVED`() {
테스트 전부 공통화 할 수 있을 것 같은데요
제 생각에는 과한 테스트 같기도 하고

결국 List에 있으면 true 아니면 false 인 것인데 너무 세분화 된 것 같아요
TURE 오타도 있네요

2023-04-02 14:21 UTC, chanqun commented on core/src/test/kotlin/io/sharing/server/core/reservation/domain/ReservationTest.kt
> +    @Test
상태에 대한 테스트가 부족한 것 같은데 우선 changeStatus를 승인 거절 같은 메소드로 변경하고 다시 보시죠

2023-04-03 11:09 UTC, NewEgoDoc commented on core/src/test/kotlin/io/sharing/server/core/reservation/domain/ReservationTest.kt
> +    @Test
넵 감사합니다.

2023-04-03 14:42 UTC, chanqun requested changes

2023-04-03 14:42 UTC, chanqun commented on core/src/test/kotlin/io/sharing/server/core/reservation/domain/ReservationTest.kt
> +    fun `예약 승인 `() {
띄어쓰기 있음

2023-04-03 14:42 UTC, chanqun commented on core/src/main/kotlin/io/sharing/server/core/reservation/domain/ReservationStatus.kt
> +    fun isAbleToChangeTo(status: ReservationStatus): Boolean {
canChangeTo 정도가 적절할 것 같습니다.

2023-04-04 13:59 UTC, NewEgoDoc commented on core/src/test/kotlin/io/sharing/server/core/reservation/domain/ReservationTest.kt
> +        reservation.status = status
apply 로 적용해서 세팅하면 될것 같습니다. 감사합니다

2023-04-04 14:47 UTC, NewEgoDoc commented on core/src/main/kotlin/io/sharing/server/core/reservation/domain/Reservation.kt
> +        this.status = APPROVED
updatedAt라는 필드를 놓고 상태가 바뀔때마다 update되는 날짜를 고려해보겠습니다. 감사합니다

2023-04-04 15:49 UTC, NewEgoDoc reviewed
- Reservation에 updatedAt(상태변경일시) 를 추가하고 상태 변경에 따른 updateAt을 업데이트합니다.
- 상태 명명 변경: DISAPPROVED -> REJECTED
- createReservation에서 status 항목을 추가하여 변경가능하게 만들었으며, 상태 변경에 따른 updateAt 시간 확인을 추가했습니다.

2023-04-05 00:04 UTC, chanqun approved these changes
updatedAt 나눠야 하는지 고민이지만
completedAt, rejectedAt처럼 우선 좋습니다

2023-04-05 13:40 UTC, merged