carsharing-57 상품 생성시 유효성 체크 기능 개발
Chanqun-Co/carsharing pull request #58
Opened 2023-04-04 15:02 UTC by kimzerovirus

상품 생성시 렌탈료와 이미지 개수 제한을 체크하도록 추가했습니다.

2023-04-04 15:34 UTC, woogiekim requested changes

2023-04-04 15:34 UTC, woogiekim commented on core/src/main/kotlin/io/sharing/server/core/product/domain/Product.kt
> +            check(images.size <= MAXIMUM_IMAGE_COUNT)
매개변수 검사이니

require가 더 좋겠습니다.

2023-04-04 15:34 UTC, woogiekim commented on core/src/test/kotlin/io/sharing/server/core/product/domain/ProductTest.kt
> +    images: MutableList<String> = mutableListOf()): Product {
```suggestion
    images: MutableList<String> = mutableListOf()
): Product {
```

이러는 편이 더 보기 좋고 일관성 있을거같아요

2023-04-05 03:19 UTC, kimzerovirus commented
넵 check -> require 수정하였습니다.

관련내용 조금 헷갈려서 코틀린 이펙티브(45p) 책 참고 하였습니다.
- require :  인자로 받은 값의 유효성을 검사할 때, ex) 입력 받은 숫자가 양의 정수여야 할 때 
- check : 어떠한 구체적인 조건을 만족하는 상태, ex) 사용자가 로그인을 했을 때

2023-04-05 14:15 UTC, woogiekim approved these changes
코멘트 남겼습니다.
반영해주신후 머지 진행하면될거같습니다.

2023-04-05 14:15 UTC, woogiekim commented on core/src/main/kotlin/io/sharing/server/core/product/domain/Product.kt
> +import org.bouncycastle.asn1.x500.style.RFC4519Style.description
이것은 무슨 의존성인가요?
안쓴다면 제거 해두는편이 좋을거같네요

2023-04-05 14:15 UTC, woogiekim commented on core/src/test/kotlin/io/sharing/server/core/product/domain/ProductTest.kt
> +    fun `상품 생성 실패 - 대여료가 정상값이 아닌 경우`() {
음수인 경우

이런이름은 어떨까 싶긴하네요

2023-04-05 15:30 UTC, merged